// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

double cpp_ordinal_loglik(const NumericMatrix& X, const IntegerVector& y, const NumericVector& beta, const int n_classes);

// cpp_ordinal_loglik
extern "C" SEXP _cosmic_cpp_ordinal_loglik(SEXP XSEXP, SEXP ySEXP, SEXP betaSEXP, SEXP n_classesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const int >::type n_classes(n_classesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ordinal_loglik(X, y, beta, n_classes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cosmic_cpp_ordinal_loglik", (DL_FUNC) &_cosmic_cpp_ordinal_loglik, 4},
    {NULL, NULL, 0}
};

extern "C" void R_init_cosmic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
