// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_cosmic_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 153> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 183, column 2 to column 22)",
  " (in 'string', line 184, column 2 to column 40)",
  " (in 'string', line 191, column 5 to column 43)",
  " (in 'string', line 190, column 2 to line 192, column 3)",
  " (in 'string', line 189, column 2 to line 192, column 3)",
  " (in 'string', line 195, column 5 to column 44)",
  " (in 'string', line 194, column 2 to line 196, column 3)",
  " (in 'string', line 193, column 2 to line 196, column 3)",
  " (in 'string', line 198, column 2 to line 200, column 21)",
  " (in 'string', line 167, column 2 to column 24)",
  " (in 'string', line 169, column 2 to column 21)",
  " (in 'string', line 170, column 2 to column 20)",
  " (in 'string', line 171, column 2 to column 26)",
  " (in 'string', line 172, column 2 to column 27)",
  " (in 'string', line 173, column 8 to column 13)",
  " (in 'string', line 173, column 2 to column 21)",
  " (in 'string', line 174, column 8 to column 13)",
  " (in 'string', line 174, column 2 to column 22)",
  " (in 'string', line 175, column 8 to column 13)",
  " (in 'string', line 175, column 2 to column 25)",
  " (in 'string', line 176, column 8 to column 18)",
  " (in 'string', line 176, column 2 to column 35)",
  " (in 'string', line 179, column 2 to column 32)",
  " (in 'string', line 180, column 2 to column 31)",
  " (in 'string', line 183, column 9 to column 13)",
  " (in 'string', line 184, column 18 to column 31)",
  " (in 'string', line 3, column 4 to column 17)",
  " (in 'string', line 4, column 4 to column 28)",
  " (in 'string', line 5, column 11 to column 12)",
  " (in 'string', line 5, column 14 to column 15)",
  " (in 'string', line 5, column 4 to column 22)",
  " (in 'string', line 6, column 4 to column 18)",
  " (in 'string', line 8, column 13 to column 14)",
  " (in 'string', line 8, column 6 to column 20)",
  " (in 'string', line 10, column 8 to column 34)",
  " (in 'string', line 9, column 6 to line 10, column 34)",
  " (in 'string', line 11, column 6 to column 39)",
  " (in 'string', line 13, column 8 to column 39)",
  " (in 'string', line 12, column 6 to line 13, column 39)",
  " (in 'string', line 14, column 6 to column 23)",
  " (in 'string', line 7, column 19 to line 15, column 5)",
  " (in 'string', line 7, column 4 to line 15, column 5)",
  " (in 'string', line 16, column 10 to column 11)",
  " (in 'string', line 16, column 4 to column 13)",
  " (in 'string', line 17, column 19 to column 28)",
  " (in 'string', line 17, column 4 to column 28)",
  " (in 'string', line 18, column 19 to column 32)",
  " (in 'string', line 18, column 4 to column 32)",
  " (in 'string', line 19, column 16 to column 28)",
  " (in 'string', line 19, column 4 to column 28)",
  " (in 'string', line 20, column 4 to column 18)",
  " (in 'string', line 21, column 13 to column 14)",
  " (in 'string', line 21, column 4 to column 16)",
  " (in 'string', line 22, column 4 to column 24)",
  " (in 'string', line 23, column 4 to column 25)",
  " (in 'string', line 25, column 6 to column 25)",
  " (in 'string', line 26, column 6 to column 26)",
  " (in 'string', line 27, column 6 to column 30)",
  " (in 'string', line 24, column 19 to line 28, column 5)",
  " (in 'string', line 24, column 4 to line 28, column 5)",
  " (in 'string', line 29, column 16 to column 17)",
  " (in 'string', line 29, column 4 to column 19)",
  " (in 'string', line 30, column 4 to column 19)",
  " (in 'string', line 32, column 6 to column 44)",
  " (in 'string', line 31, column 4 to line 32, column 44)",
  " (in 'string', line 33, column 11 to column 23)",
  " (in 'string', line 33, column 4 to column 36)",
  " (in 'string', line 34, column 11 to column 23)",
  " (in 'string', line 34, column 4 to column 36)",
  " (in 'string', line 35, column 4 to column 63)",
  " (in 'string', line 36, column 4 to column 22)",
  " (in 'string', line 37, column 4 to column 18)",
  " (in 'string', line 38, column 10 to column 11)",
  " (in 'string', line 38, column 4 to column 13)",
  " (in 'string', line 40, column 6 to column 65)",
  " (in 'string', line 41, column 6 to column 34)",
  " (in 'string', line 42, column 6 to column 37)",
  " (in 'string', line 43, column 21 to column 30)",
  " (in 'string', line 43, column 6 to column 30)",
  " (in 'string', line 44, column 6 to column 20)",
  " (in 'string', line 46, column 8 to column 35)",
  " (in 'string', line 49, column 10 to line 51, column 42)",
  " (in 'string', line 55, column 14 to column 45)",
  " (in 'string', line 56, column 14 to line 58, column 46)",
  " (in 'string', line 54, column 29 to line 59, column 13)",
  " (in 'string', line 54, column 12 to line 59, column 13)",
  " (in 'string', line 53, column 25 to line 60, column 11)",
  " (in 'string', line 53, column 10 to line 60, column 11)",
  " (in 'string', line 47, column 40 to line 61, column 9)",
  " (in 'string', line 47, column 8 to line 61, column 9)",
  " (in 'string', line 64, column 10 to column 20)",
  " (in 'string', line 65, column 10 to column 21)",
  " (in 'string', line 67, column 12 to column 18)",
  " (in 'string', line 66, column 10 to line 67, column 18)",
  " (in 'string', line 68, column 10 to column 24)",
  " (in 'string', line 69, column 10 to column 19)",
  " (in 'string', line 63, column 23 to line 70, column 9)",
  " (in 'string', line 63, column 8 to line 70, column 9)",
  " (in 'string', line 45, column 34 to line 71, column 7)",
  " (in 'string', line 45, column 6 to line 71, column 7)",
  " (in 'string', line 72, column 6 to column 30)",
  " (in 'string', line 39, column 19 to line 73, column 5)",
  " (in 'string', line 39, column 4 to line 73, column 5)",
  " (in 'string', line 74, column 4 to column 23)",
  " (in 'string', line 76, column 6 to column 38)",
  " (in 'string', line 75, column 4 to line 76, column 38)",
  " (in 'string', line 77, column 4 to column 41)",
  " (in 'string', line 2, column 71 to line 78, column 3)",
  " (in 'string', line 90, column 4 to column 13)",
  " (in 'string', line 91, column 4 to column 24)",
  " (in 'string', line 92, column 4 to column 18)",
  " (in 'string', line 93, column 4 to column 22)",
  " (in 'string', line 94, column 4 to column 26)",
  " (in 'string', line 95, column 10 to column 18)",
  " (in 'string', line 95, column 4 to column 32)",
  " (in 'string', line 96, column 11 to column 19)",
  " (in 'string', line 96, column 4 to column 37)",
  " (in 'string', line 98, column 4 to column 24)",
  " (in 'string', line 101, column 6 to column 15)",
  " (in 'string', line 102, column 6 to column 23)",
  " (in 'string', line 103, column 6 to column 27)",
  " (in 'string', line 107, column 9 to column 60)",
  " (in 'string', line 109, column 9 to column 23)",
  " (in 'string', line 110, column 9 to column 32)",
  " (in 'string', line 111, column 9 to column 51)",
  " (in 'string', line 112, column 9 to column 17)",
  " (in 'string', line 105, column 6 to line 113, column 7)",
  " (in 'string', line 104, column 6 to line 113, column 7)",
  " (in 'string', line 127, column 8 to line 128, column 69)",
  " (in 'string', line 126, column 11 to line 129, column 7)",
  " (in 'string', line 118, column 10 to line 119, column 57)",
  " (in 'string', line 120, column 10 to line 121, column 57)",
  " (in 'string', line 122, column 10 to column 51)",
  " (in 'string', line 117, column 8 to line 123, column 9)",
  " (in 'string', line 116, column 8 to line 123, column 9)",
  " (in 'string', line 115, column 6 to line 125, column 7)",
  " (in 'string', line 114, column 6 to line 129, column 7)",
  " (in 'string', line 100, column 4 to line 130, column 5)",
  " (in 'string', line 99, column 4 to line 130, column 5)",
  " (in 'string', line 131, column 4 to column 18)",
  " (in 'string', line 89, column 2 to line 132, column 3)",
  " (in 'string', line 145, column 11 to column 22)",
  " (in 'string', line 145, column 4 to column 32)",
  " (in 'string', line 146, column 4 to column 22)",
  " (in 'string', line 147, column 4 to column 21)",
  " (in 'string', line 148, column 4 to column 21)",
  " (in 'string', line 151, column 6 to column 48)",
  " (in 'string', line 150, column 4 to line 152, column 5)",
  " (in 'string', line 149, column 4 to line 152, column 5)",
  " (in 'string', line 154, column 4 to line 162, column 34)",
  " (in 'string', line 163, column 4 to column 18)",
  " (in 'string', line 144, column 2 to line 164, column 3)"};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>>
logDenomDP_logspace(const T0__& lambda_arg__, const T1__& s_arg__,
                    const std::vector<int>& y, const int& nOff, std::ostream*
                    pstream__);
template <typename T6__, typename T7__,
          stan::require_all_t<stan::is_col_vector<T6__>,
                              stan::is_vt_not_complex<T6__>,
                              stan::is_col_vector<T7__>,
                              stan::is_vt_not_complex<T7__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T6__>, stan::base_type_t<T7__>>
partial_sum(const std::vector<int>& iaIndexStart, const int& iStart,
            const int& iEnd, const std::vector<int>& ivY,
            const std::vector<int>& ivID, const std::vector<int>& ivOffID,
            const T6__& rvLambda_arg__, const T7__& rvSTemp_arg__, const int&
            nRows, const int& nMaxOffs, std::ostream* pstream__);
template <typename T4__, typename T5__,
          stan::require_all_t<stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::is_col_vector<T5__>,
                              stan::is_vt_not_complex<T5__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T4__>, stan::base_type_t<T5__>>
logCL(const std::vector<int>& ivY, const std::vector<int>& ivID,
      const std::vector<int>& ivOffID, const std::vector<int>& ivStartIndex,
      const T4__& rvLambda_arg__, const T5__& rvSDelta_arg__, const int&
      nRows, const int& nMaxOffs, const int& nForceTypes, const int&
      grainsize, std::ostream* pstream__);
struct partial_sum_rsfunctor__ {
  template <typename T6__, typename T7__,
            stan::require_all_t<stan::is_col_vector<T6__>,
                                stan::is_vt_not_complex<T6__>,
                                stan::is_col_vector<T7__>,
                                stan::is_vt_not_complex<T7__>>* = nullptr>
  stan::promote_args_t<stan::base_type_t<T6__>, stan::base_type_t<T7__>>
  operator()(const std::vector<int>& iaIndexStart, const int& iStart,
             const int& iEnd, std::ostream* pstream__,
             const std::vector<int>& ivY, const std::vector<int>& ivID,
             const std::vector<int>& ivOffID, const T6__& rvLambda,
             const T7__& rvSTemp, const int& nRows, const int& nMaxOffs) const {
    return partial_sum(iaIndexStart, (iStart + 1), (iEnd + 1), ivY, ivID,
             ivOffID, rvLambda, rvSTemp, nRows, nMaxOffs, pstream__);
  }
};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>>
logDenomDP_logspace(const T0__& lambda_arg__, const T1__& s_arg__,
                    const std::vector<int>& y, const int& nOff, std::ostream*
                    pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& lambda = stan::math::to_ref(lambda_arg__);
  const auto& s = stan::math::to_ref(s_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int m = std::numeric_limits<int>::min();
    current_statement__ = 27;
    m = nOff;
    int J = std::numeric_limits<int>::min();
    current_statement__ = 28;
    J = stan::math::num_elements(s);
    current_statement__ = 29;
    stan::math::validate_non_negative_index("logP", "m", m);
    current_statement__ = 30;
    stan::math::validate_non_negative_index("logP", "J", J);
    Eigen::Matrix<local_scalar_t__,-1,-1> logP =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(m, J, DUMMY_VAR__);
    local_scalar_t__ logK = DUMMY_VAR__;
    current_statement__ = 32;
    logK = 0;
    current_statement__ = 42;
    for (int i = 1; i <= m; ++i) {
      current_statement__ = 33;
      stan::math::validate_non_negative_index("eta", "J", J);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 36;
      for (int j = 1; j <= J; ++j) {
        current_statement__ = 35;
        stan::model::assign(eta,
          (stan::model::rvalue(lambda, "lambda", stan::model::index_uni(i)) *
          stan::model::rvalue(s, "s", stan::model::index_uni(j))),
          "assigning variable eta", stan::model::index_uni(j));
      }
      local_scalar_t__ log_norm = DUMMY_VAR__;
      current_statement__ = 37;
      log_norm = stan::math::log_sum_exp(eta);
      current_statement__ = 39;
      for (int j = 1; j <= J; ++j) {
        current_statement__ = 38;
        stan::model::assign(logP,
          (stan::model::rvalue(eta, "eta", stan::model::index_uni(j)) -
          log_norm), "assigning variable logP", stan::model::index_uni(i),
          stan::model::index_uni(j));
      }
      current_statement__ = 40;
      logK = (logK + log_norm);
    }
    current_statement__ = 43;
    stan::math::validate_non_negative_index("k", "J", J);
    std::vector<int> k = std::vector<int>(J, std::numeric_limits<int>::min());
    current_statement__ = 46;
    for (int j = 1; j <= J; ++j) {
      current_statement__ = 45;
      stan::model::assign(k, 0, "assigning variable k",
        stan::model::index_uni(j));
    }
    current_statement__ = 48;
    for (int i = 1; i <= m; ++i) {
      current_statement__ = 47;
      stan::model::assign(k,
        (stan::model::rvalue(k, "k",
           stan::model::index_uni(
             stan::model::rvalue(y, "y", stan::model::index_uni(i)))) + 1),
        "assigning variable k",
        stan::model::index_uni(
          stan::model::rvalue(y, "y", stan::model::index_uni(i))));
    }
    current_statement__ = 50;
    if (stan::math::logical_eq(J, 1)) {
      current_statement__ = 49;
      return logK;
    }
    int d = std::numeric_limits<int>::min();
    current_statement__ = 51;
    d = (J - 1);
    current_statement__ = 52;
    stan::math::validate_non_negative_index("dims", "d", d);
    std::vector<int> dims =
      std::vector<int>(d, std::numeric_limits<int>::min());
    int total_non_J = std::numeric_limits<int>::min();
    current_statement__ = 54;
    total_non_J = 0;
    int total_states = std::numeric_limits<int>::min();
    current_statement__ = 55;
    total_states = 1;
    current_statement__ = 60;
    for (int j = 1; j <= d; ++j) {
      current_statement__ = 56;
      stan::model::assign(dims,
        (stan::model::rvalue(k, "k", stan::model::index_uni(j)) + 1),
        "assigning variable dims", stan::model::index_uni(j));
      current_statement__ = 57;
      total_non_J = (total_non_J +
        stan::model::rvalue(k, "k", stan::model::index_uni(j)));
      current_statement__ = 58;
      total_states = (total_states *
        stan::model::rvalue(dims, "dims", stan::model::index_uni(j)));
    }
    current_statement__ = 61;
    stan::math::validate_non_negative_index("strides", "d", d);
    std::vector<int> strides =
      std::vector<int>(d, std::numeric_limits<int>::min());
    current_statement__ = 63;
    stan::model::assign(strides, 1, "assigning variable strides",
      stan::model::index_uni(1));
    current_statement__ = 65;
    for (int j = 2; j <= d; ++j) {
      current_statement__ = 64;
      stan::model::assign(strides,
        (stan::model::rvalue(strides, "strides",
           stan::model::index_uni((j - 1))) *
        stan::model::rvalue(dims, "dims", stan::model::index_uni((j - 1)))),
        "assigning variable strides", stan::model::index_uni(j));
    }
    current_statement__ = 66;
    stan::math::validate_non_negative_index("log_dp_old", "total_states",
      total_states);
    Eigen::Matrix<local_scalar_t__,-1,1> log_dp_old =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(total_states,
        DUMMY_VAR__);
    current_statement__ = 68;
    stan::math::validate_non_negative_index("log_dp_new", "total_states",
      total_states);
    Eigen::Matrix<local_scalar_t__,-1,1> log_dp_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(total_states,
        DUMMY_VAR__);
    current_statement__ = 70;
    stan::model::assign(log_dp_old,
      stan::math::rep_vector(stan::math::negative_infinity(), total_states),
      "assigning variable log_dp_old");
    current_statement__ = 71;
    stan::model::assign(log_dp_old, 0, "assigning variable log_dp_old",
      stan::model::index_uni(1));
    int kJ = std::numeric_limits<int>::min();
    current_statement__ = 72;
    kJ = stan::model::rvalue(k, "k", stan::model::index_uni(J));
    current_statement__ = 73;
    stan::math::validate_non_negative_index("u", "d", d);
    std::vector<int> u = std::vector<int>(d, std::numeric_limits<int>::min());
    current_statement__ = 103;
    for (int r = 1; r <= m; ++r) {
      current_statement__ = 75;
      stan::model::assign(log_dp_new,
        stan::math::rep_vector(stan::math::negative_infinity(), total_states),
        "assigning variable log_dp_new");
      int lo = std::numeric_limits<int>::min();
      current_statement__ = 76;
      lo = stan::math::max(0, ((r - 1) - kJ));
      int hi = std::numeric_limits<int>::min();
      current_statement__ = 77;
      hi = stan::math::min((r - 1), total_non_J);
      current_statement__ = 79;
      for (int j = 1; j <= d; ++j) {
        current_statement__ = 78;
        stan::model::assign(u, 0, "assigning variable u",
          stan::model::index_uni(j));
      }
      int sum_u = std::numeric_limits<int>::min();
      current_statement__ = 80;
      sum_u = 0;
      current_statement__ = 100;
      for (int idx = 1; idx <= total_states; ++idx) {
        local_scalar_t__ val = DUMMY_VAR__;
        current_statement__ = 81;
        val = stan::model::rvalue(log_dp_old, "log_dp_old",
                stan::model::index_uni(idx));
        current_statement__ = 90;
        if ((stan::math::primitive_value(stan::math::logical_gte(sum_u, lo))
            &&
            stan::math::primitive_value(stan::math::logical_lte(sum_u, hi)))) {
          current_statement__ = 82;
          stan::model::assign(log_dp_new,
            stan::math::log_sum_exp(
              stan::model::rvalue(log_dp_new, "log_dp_new",
                stan::model::index_uni(idx)), (val +
              stan::model::rvalue(logP, "logP", stan::model::index_uni(r),
                stan::model::index_uni(J)))),
            "assigning variable log_dp_new", stan::model::index_uni(idx));
          current_statement__ = 88;
          for (int j = 1; j <= d; ++j) {
            current_statement__ = 86;
            if (stan::math::logical_lt(
                  stan::model::rvalue(u, "u", stan::model::index_uni(j)),
                  stan::model::rvalue(k, "k", stan::model::index_uni(j)))) {
              int new_idx = std::numeric_limits<int>::min();
              current_statement__ = 83;
              new_idx = (idx +
                stan::model::rvalue(strides, "strides",
                  stan::model::index_uni(j)));
              current_statement__ = 84;
              stan::model::assign(log_dp_new,
                stan::math::log_sum_exp(
                  stan::model::rvalue(log_dp_new, "log_dp_new",
                    stan::model::index_uni(new_idx)), (val +
                  stan::model::rvalue(logP, "logP",
                    stan::model::index_uni(r), stan::model::index_uni(j)))),
                "assigning variable log_dp_new",
                stan::model::index_uni(new_idx));
            }
          }
        }
        current_statement__ = 98;
        for (int j = 1; j <= d; ++j) {
          current_statement__ = 91;
          stan::model::assign(u,
            (stan::model::rvalue(u, "u", stan::model::index_uni(j)) + 1),
            "assigning variable u", stan::model::index_uni(j));
          current_statement__ = 92;
          sum_u = (sum_u + 1);
          current_statement__ = 94;
          if (stan::math::logical_lt(
                stan::model::rvalue(u, "u", stan::model::index_uni(j)),
                stan::model::rvalue(dims, "dims", stan::model::index_uni(j)))) {
            break;
          }
          current_statement__ = 95;
          sum_u = (sum_u -
            stan::model::rvalue(u, "u", stan::model::index_uni(j)));
          current_statement__ = 96;
          stan::model::assign(u, 0, "assigning variable u",
            stan::model::index_uni(j));
        }
      }
      current_statement__ = 101;
      stan::model::assign(log_dp_old, log_dp_new,
        "assigning variable log_dp_old");
    }
    int target_idx = std::numeric_limits<int>::min();
    current_statement__ = 104;
    target_idx = 1;
    current_statement__ = 106;
    for (int j = 1; j <= d; ++j) {
      current_statement__ = 105;
      target_idx = (target_idx +
        (stan::model::rvalue(k, "k", stan::model::index_uni(j)) *
        stan::model::rvalue(strides, "strides", stan::model::index_uni(j))));
    }
    current_statement__ = 107;
    return (logK +
           stan::model::rvalue(log_dp_old, "log_dp_old",
             stan::model::index_uni(target_idx)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T6__, typename T7__,
          stan::require_all_t<stan::is_col_vector<T6__>,
                              stan::is_vt_not_complex<T6__>,
                              stan::is_col_vector<T7__>,
                              stan::is_vt_not_complex<T7__>>*>
stan::promote_args_t<stan::base_type_t<T6__>, stan::base_type_t<T7__>>
partial_sum(const std::vector<int>& iaIndexStart, const int& iStart,
            const int& iEnd, const std::vector<int>& ivY,
            const std::vector<int>& ivID, const std::vector<int>& ivOffID,
            const T6__& rvLambda_arg__, const T7__& rvSTemp_arg__, const int&
            nRows, const int& nMaxOffs, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T6__>,
                             stan::base_type_t<T7__>>;
  int current_statement__ = 0;
  const auto& rvLambda = stan::math::to_ref(rvLambda_arg__);
  const auto& rvSTemp = stan::math::to_ref(rvSTemp_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int i = std::numeric_limits<int>::min();
    current_statement__ = 109;
    i = 0;
    int iCurrentID = std::numeric_limits<int>::min();
    current_statement__ = 110;
    iCurrentID = 0;
    int nOff = std::numeric_limits<int>::min();
    current_statement__ = 111;
    nOff = 0;
    local_scalar_t__ rLogLL = DUMMY_VAR__;
    current_statement__ = 112;
    rLogLL = 0.0;
    local_scalar_t__ rNumerator = DUMMY_VAR__;
    current_statement__ = 113;
    rNumerator = 0.0;
    current_statement__ = 114;
    stan::math::validate_non_negative_index("ivYTemp", "nMaxOffs", nMaxOffs);
    std::vector<int> ivYTemp =
      std::vector<int>(nMaxOffs, std::numeric_limits<int>::min());
    current_statement__ = 116;
    stan::math::validate_non_negative_index("rvLambdaTemp", "nMaxOffs",
      nMaxOffs);
    Eigen::Matrix<local_scalar_t__,-1,1> rvLambdaTemp =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nMaxOffs, DUMMY_VAR__);
    current_statement__ = 118;
    i = stan::model::rvalue(iaIndexStart, "iaIndexStart",
          stan::model::index_uni(1));
    current_statement__ = 139;
    while ((stan::math::primitive_value(stan::math::logical_lte(i, nRows)) &&
           stan::math::primitive_value(
             stan::math::logical_lte(
               stan::model::rvalue(ivID, "ivID", stan::model::index_uni(i)),
               iEnd)))) {
      current_statement__ = 119;
      nOff = 0;
      current_statement__ = 120;
      rNumerator = 0.0;
      current_statement__ = 121;
      iCurrentID = stan::model::rvalue(ivID, "ivID",
                     stan::model::index_uni(i));
      current_statement__ = 128;
      while ((stan::math::primitive_value(stan::math::logical_lte(i, nRows))
             &&
             stan::math::primitive_value(
               stan::math::logical_eq(
                 stan::model::rvalue(ivID, "ivID", stan::model::index_uni(i)),
                 iCurrentID)))) {
        current_statement__ = 122;
        rNumerator = (rNumerator +
          (stan::model::rvalue(rvLambda, "rvLambda",
             stan::model::index_uni(
               stan::model::rvalue(ivOffID, "ivOffID",
                 stan::model::index_uni(i))))
          *
          stan::model::rvalue(rvSTemp, "rvSTemp",
            stan::model::index_uni(
              stan::model::rvalue(ivY, "ivY", stan::model::index_uni(i))))));
        current_statement__ = 123;
        nOff = (nOff + 1);
        current_statement__ = 124;
        stan::model::assign(ivYTemp,
          stan::model::rvalue(ivY, "ivY", stan::model::index_uni(i)),
          "assigning variable ivYTemp", stan::model::index_uni(nOff));
        current_statement__ = 125;
        stan::model::assign(rvLambdaTemp,
          stan::model::rvalue(rvLambda, "rvLambda",
            stan::model::index_uni(
              stan::model::rvalue(ivOffID, "ivOffID",
                stan::model::index_uni(i)))),
          "assigning variable rvLambdaTemp", stan::model::index_uni(nOff));
        current_statement__ = 126;
        i = (i + 1);
      }
      current_statement__ = 137;
      if (stan::math::logical_eq(nOff, 2)) {
        current_statement__ = 135;
        if (stan::math::logical_neq(
              stan::model::rvalue(ivYTemp, "ivYTemp",
                stan::model::index_uni(1)),
              stan::model::rvalue(ivYTemp, "ivYTemp",
                stan::model::index_uni(2)))) {
          local_scalar_t__ a = DUMMY_VAR__;
          current_statement__ = 131;
          a = ((stan::model::rvalue(rvLambdaTemp, "rvLambdaTemp",
                  stan::model::index_uni(1))
            *
            stan::model::rvalue(rvSTemp, "rvSTemp",
              stan::model::index_uni(
                stan::model::rvalue(ivYTemp, "ivYTemp",
                  stan::model::index_uni(1)))))
            +
            (stan::model::rvalue(rvLambdaTemp, "rvLambdaTemp",
               stan::model::index_uni(2))
            *
            stan::model::rvalue(rvSTemp, "rvSTemp",
              stan::model::index_uni(
                stan::model::rvalue(ivYTemp, "ivYTemp",
                  stan::model::index_uni(2))))));
          local_scalar_t__ b = DUMMY_VAR__;
          current_statement__ = 132;
          b = ((stan::model::rvalue(rvLambdaTemp, "rvLambdaTemp",
                  stan::model::index_uni(1))
            *
            stan::model::rvalue(rvSTemp, "rvSTemp",
              stan::model::index_uni(
                stan::model::rvalue(ivYTemp, "ivYTemp",
                  stan::model::index_uni(2)))))
            +
            (stan::model::rvalue(rvLambdaTemp, "rvLambdaTemp",
               stan::model::index_uni(2))
            *
            stan::model::rvalue(rvSTemp, "rvSTemp",
              stan::model::index_uni(
                stan::model::rvalue(ivYTemp, "ivYTemp",
                  stan::model::index_uni(1))))));
          current_statement__ = 133;
          rLogLL = (rLogLL + (rNumerator - stan::math::log_sum_exp(a, b)));
        }
      } else {
        current_statement__ = 129;
        rLogLL = (rLogLL + (rNumerator -
          logDenomDP_logspace(rvLambdaTemp, rvSTemp, ivYTemp, nOff, pstream__)));
      }
    }
    current_statement__ = 140;
    return rLogLL;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T4__, typename T5__,
          stan::require_all_t<stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::is_col_vector<T5__>,
                              stan::is_vt_not_complex<T5__>>*>
stan::promote_args_t<stan::base_type_t<T4__>, stan::base_type_t<T5__>>
logCL(const std::vector<int>& ivY, const std::vector<int>& ivID,
      const std::vector<int>& ivOffID, const std::vector<int>& ivStartIndex,
      const T4__& rvLambda_arg__, const T5__& rvSDelta_arg__, const int&
      nRows, const int& nMaxOffs, const int& nForceTypes, const int&
      grainsize, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T4__>,
                             stan::base_type_t<T5__>>;
  int current_statement__ = 0;
  const auto& rvLambda = stan::math::to_ref(rvLambda_arg__);
  const auto& rvSDelta = stan::math::to_ref(rvSDelta_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 142;
    stan::math::validate_non_negative_index("rvSTemp", "nForceTypes",
      nForceTypes);
    Eigen::Matrix<local_scalar_t__,-1,1> rvSTemp =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nForceTypes,
        DUMMY_VAR__);
    local_scalar_t__ rLogLL = DUMMY_VAR__;
    current_statement__ = 144;
    rLogLL = 0.0;
    current_statement__ = 145;
    stan::model::assign(rvSTemp, 0.0, "assigning variable rvSTemp",
      stan::model::index_uni(1));
    current_statement__ = 146;
    stan::model::assign(rvSTemp, 1.0, "assigning variable rvSTemp",
      stan::model::index_uni(2));
    current_statement__ = 149;
    for (int k = 3; k <= nForceTypes; ++k) {
      current_statement__ = 147;
      stan::model::assign(rvSTemp,
        (stan::model::rvalue(rvSTemp, "rvSTemp",
           stan::model::index_uni((k - 1))) +
        stan::model::rvalue(rvSDelta, "rvSDelta",
          stan::model::index_uni((k - 2)))), "assigning variable rvSTemp",
        stan::model::index_uni(k));
    }
    current_statement__ = 150;
    rLogLL = stan::math::reduce_sum<partial_sum_rsfunctor__>(ivStartIndex,
               grainsize, pstream__, ivY, ivID, ivOffID, rvLambda, rvSTemp,
               nRows, nMaxOffs);
    current_statement__ = 151;
    return rLogLL;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_cosmic final : public model_base_crtp<model_cosmic> {
private:
  int nMaxOffs;
  int nRows;
  int nOff;
  int nIncidents;
  int nForceTypes;
  std::vector<int> y;
  std::vector<int> id;
  std::vector<int> idOff;
  std::vector<int> startIndex;
  double rPriorSD_lambda;
  double rPriorSD_sDiff;
  int sDelta_1dim__;
public:
  ~model_cosmic() {}
  model_cosmic(stan::io::var_context& context__, unsigned int
               random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_cosmic_namespace::model_cosmic";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 10;
      context__.validate_dims("data initialization", "nMaxOffs", "int",
        std::vector<size_t>{});
      nMaxOffs = std::numeric_limits<int>::min();
      current_statement__ = 10;
      nMaxOffs = context__.vals_i("nMaxOffs")[(1 - 1)];
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "nMaxOffs", nMaxOffs, 0);
      current_statement__ = 11;
      context__.validate_dims("data initialization", "nRows", "int",
        std::vector<size_t>{});
      nRows = std::numeric_limits<int>::min();
      current_statement__ = 11;
      nRows = context__.vals_i("nRows")[(1 - 1)];
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "nRows", nRows, 0);
      current_statement__ = 12;
      context__.validate_dims("data initialization", "nOff", "int",
        std::vector<size_t>{});
      nOff = std::numeric_limits<int>::min();
      current_statement__ = 12;
      nOff = context__.vals_i("nOff")[(1 - 1)];
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "nOff", nOff, 0);
      current_statement__ = 13;
      context__.validate_dims("data initialization", "nIncidents", "int",
        std::vector<size_t>{});
      nIncidents = std::numeric_limits<int>::min();
      current_statement__ = 13;
      nIncidents = context__.vals_i("nIncidents")[(1 - 1)];
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "nIncidents",
        nIncidents, 0);
      current_statement__ = 14;
      context__.validate_dims("data initialization", "nForceTypes", "int",
        std::vector<size_t>{});
      nForceTypes = std::numeric_limits<int>::min();
      current_statement__ = 14;
      nForceTypes = context__.vals_i("nForceTypes")[(1 - 1)];
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "nForceTypes",
        nForceTypes, 0);
      current_statement__ = 15;
      stan::math::validate_non_negative_index("y", "nRows", nRows);
      current_statement__ = 16;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(nRows)});
      y = std::vector<int>(nRows, std::numeric_limits<int>::min());
      current_statement__ = 16;
      y = context__.vals_i("y");
      current_statement__ = 17;
      stan::math::validate_non_negative_index("id", "nRows", nRows);
      current_statement__ = 18;
      context__.validate_dims("data initialization", "id", "int",
        std::vector<size_t>{static_cast<size_t>(nRows)});
      id = std::vector<int>(nRows, std::numeric_limits<int>::min());
      current_statement__ = 18;
      id = context__.vals_i("id");
      current_statement__ = 19;
      stan::math::validate_non_negative_index("idOff", "nRows", nRows);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "idOff", "int",
        std::vector<size_t>{static_cast<size_t>(nRows)});
      idOff = std::vector<int>(nRows, std::numeric_limits<int>::min());
      current_statement__ = 20;
      idOff = context__.vals_i("idOff");
      current_statement__ = 21;
      stan::math::validate_non_negative_index("startIndex", "nIncidents",
        nIncidents);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "startIndex", "int",
        std::vector<size_t>{static_cast<size_t>(nIncidents)});
      startIndex = std::vector<int>(nIncidents,
                     std::numeric_limits<int>::min());
      current_statement__ = 22;
      startIndex = context__.vals_i("startIndex");
      current_statement__ = 23;
      context__.validate_dims("data initialization", "rPriorSD_lambda",
        "double", std::vector<size_t>{});
      rPriorSD_lambda = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 23;
      rPriorSD_lambda = context__.vals_r("rPriorSD_lambda")[(1 - 1)];
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "rPriorSD_lambda",
        rPriorSD_lambda, 0);
      current_statement__ = 24;
      context__.validate_dims("data initialization", "rPriorSD_sDiff",
        "double", std::vector<size_t>{});
      rPriorSD_sDiff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 24;
      rPriorSD_sDiff = context__.vals_r("rPriorSD_sDiff")[(1 - 1)];
      current_statement__ = 24;
      stan::math::check_greater_or_equal(function__, "rPriorSD_sDiff",
        rPriorSD_sDiff, 0);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("lambda", "nOff", nOff);
      current_statement__ = 26;
      sDelta_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 26;
      sDelta_1dim__ = (nForceTypes - 2);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("sDelta", "nForceTypes - 2",
        sDelta_1dim__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = nOff + sDelta_1dim__;
  }
  inline std::string model_name() const final {
    return "model_cosmic";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_cosmic_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> lambda =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nOff, DUMMY_VAR__);
      current_statement__ = 1;
      lambda = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nOff);
      Eigen::Matrix<local_scalar_t__,-1,1> sDelta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(sDelta_1dim__,
          DUMMY_VAR__);
      current_statement__ = 2;
      sDelta = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 sDelta_1dim__);
      {
        current_statement__ = 5;
        for (int i = 1; i <= (nForceTypes - 2); ++i) {
          current_statement__ = 3;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(sDelta, "sDelta",
                             stan::model::index_uni(i)), 0, rPriorSD_sDiff));
        }
        current_statement__ = 8;
        for (int i = 1; i <= nOff; ++i) {
          current_statement__ = 6;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(lambda, "lambda",
                             stan::model::index_uni(i)), 0, rPriorSD_lambda));
        }
        current_statement__ = 9;
        lp_accum__.add(logCL(y, id, idOff, startIndex, lambda, sDelta, nRows,
                         nMaxOffs, nForceTypes, 1, pstream__));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_cosmic_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> lambda =
        Eigen::Matrix<double,-1,1>::Constant(nOff,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      lambda = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nOff);
      Eigen::Matrix<double,-1,1> sDelta =
        Eigen::Matrix<double,-1,1>::Constant(sDelta_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      sDelta = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 sDelta_1dim__);
      out__.write(lambda);
      out__.write(sDelta);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> lambda =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nOff, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(lambda,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nOff),
        "assigning variable lambda");
      out__.write(lambda);
      Eigen::Matrix<local_scalar_t__,-1,1> sDelta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(sDelta_1dim__,
          DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(sDelta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(sDelta_1dim__),
        "assigning variable sDelta");
      out__.write_free_lb(0, sDelta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "lambda", "double",
        std::vector<size_t>{static_cast<size_t>(nOff)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sDelta", "double",
        std::vector<size_t>{static_cast<size_t>(sDelta_1dim__)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> lambda =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nOff, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> lambda_flat__;
        current_statement__ = 1;
        lambda_flat__ = context__.vals_r("lambda");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= nOff; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(lambda, lambda_flat__[(pos__ - 1)],
            "assigning variable lambda", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(lambda);
      Eigen::Matrix<local_scalar_t__,-1,1> sDelta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(sDelta_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sDelta_flat__;
        current_statement__ = 2;
        sDelta_flat__ = context__.vals_r("sDelta");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= sDelta_1dim__; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(sDelta, sDelta_flat__[(pos__ - 1)],
            "assigning variable sDelta", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sDelta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"lambda", "sDelta"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    nOff)},
                std::vector<size_t>{static_cast<size_t>(sDelta_1dim__)}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= nOff; ++sym1__) {
      param_names__.emplace_back(std::string() + "lambda" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= sDelta_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "sDelta" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= nOff; ++sym1__) {
      param_names__.emplace_back(std::string() + "lambda" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= sDelta_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "sDelta" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nOff) + "},\"block\":\"parameters\"},{\"name\":\"sDelta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(sDelta_1dim__) + "},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nOff) + "},\"block\":\"parameters\"},{\"name\":\"sDelta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(sDelta_1dim__) + "},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (nOff + sDelta_1dim__);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (nOff + sDelta_1dim__);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_cosmic_namespace::model_cosmic;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_cosmic_namespace::profiles__;
}
#endif
#endif
