# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_ordinal_loglik <- function(X, y, beta, n_classes) {
    .Call(`_cosmic_cpp_ordinal_loglik`, X, y, beta, n_classes)
}
